
D2L.Control.UserProfile=D2L.Control.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_maxImageSize=0},IntegrateControlMin:function(deserializer){arguments.callee.$.IntegrateControlMin.call(this);this.m_maxImageSize=deserializer.GetMember()},ChangePicture:function(){var me=this;var callback=function(dialogResponse){if(dialogResponse.GetType()==D2L.Dialog.ResponseType.Positive){var files=dialogResponse.GetData("files");if(files&&files.length==1){var file=files[0];var profile=
UI.GetControl(me.GetMappedId()+"_UP_profile");var remove=UI.GetControl("IMG_removePicture");remove.SetIsDisplayed(true);UI.GetControl("HDN_pictureHasChanged").SetValue("1");UI.GetControl("HDN_pictureFileId").SetValue(file.GetFileId());UI.GetControl("HDN_pictureFST").SetValue(file.GetFileSystemType());UI.GetControl("HDN_pictureFileSize").SetValue(file.GetSize());profile.SetProfileImage(file);FormManager.ForceChange(profile)}}dialogResponse.GetDialog().Close()};var selectFileDialog=new D2L.Dialog.SelectFile(callback);
selectFileDialog.SetTitle(new D2L.LP.Text.LangTerm("Profile.select_picture.titSelectPicture"));selectFileDialog.SetFileFilters([D2L.Files.FilterType.Images]);selectFileDialog.SetAreaFilters([D2L.Files.Area.MyComputer,D2L.Files.Area.MyLocker]);selectFileDialog.SetAllowMultiple(false);selectFileDialog.SetMaxFileSize(this.m_maxImageSize);selectFileDialog.Open()},RemovePicture:function(){var me=this;var callback=function(response){if(response.GetType()==D2L.Dialog.ResponseType.Positive){var profile=UI.GetControl(me.GetMappedId()+
"_UP_profile");var remove=UI.GetControl("IMG_removePicture");profile.SetProfileImage(null);remove.SetIsDisplayed(false);UI.GetControl("HDN_pictureHasChanged").SetValue("1");UI.GetControl("HDN_pictureFileId").SetValue("");UI.GetControl("HDN_pictureFST").SetValue("");UI.GetControl("HDN_pictureFileSize").SetValue("");FormManager.ForceChange(profile)}};var confirm=new D2L.Dialog.Confirm("confirm_delete",callback,new D2L.LP.Text.LangTerm("Profile.select_picture.lblRemovePictureConfirmPrimary"),new D2L.LP.Text.LangTerm("Profile.select_picture.lblRemovePictureConfirmSecondary"));
confirm.SetNegativeButtonText(new D2L.LP.Text.LangTerm("Standard.Buttons.btnCancel"));confirm.SetPositiveButtonText(new D2L.LP.Text.LangTerm("Profile.select_picture.btnRemove"));confirm.Open()}});D2L.Control.UserProfile.ValidateBirthdayRequired=function(){var slMonth=UI.GetControl("SL_month");var slDay=UI.GetControl("SL_day");if(slMonth&&slDay){var m=slMonth.GetSelectedValue();var d=slDay.GetSelectedValue();return m>0||d>0}return true};
D2L.Control.UserProfile.ValidateBirthday=function(vObj){var slMonth=UI.GetControl("SL_month");var slDay=UI.GetControl("SL_day");if(slMonth&&slDay){var m=slMonth.GetSelectedValue();var d=slDay.GetSelectedValue();if(m==0&&d!=0||m!=0&&d==0)return false;var allowedDays=31;if(m==2)allowedDays=29;else if(m==4||m==6||m==9||m==11)allowedDays=30;if(d>allowedDays){vObj.SetFailureControl(slDay);return false}}return true};
D2L.Control.UserProfile.ValidatePicture=function(){var fileId=UI.GetControl("HDN_pictureFileId").GetValue();if(fileId.length===0)return false;return true};D2L.Control.UserProfile.ValidatePictureSize=function(){var fileSize=UI.GetControl("HDN_pictureFileSize").GetValue();var maxImageSize=UI.GetControl("HDN_pictureMaxFileSize").GetValue();if(fileSize!=""&&maxImageSize!=""&&parseInt(fileSize)>parseInt(maxImageSize))return false;return true};
D2L.Control.ProfileBadgeImage=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_src="";this.m_size=100},Deserialize:function(deserializer){this.m_src=deserializer.GetMember("Src");this.m_size=deserializer.GetMember("Size")},DeserializeMin:function(deserializer){this.m_src=deserializer.GetMember();this.m_size=deserializer.GetMember()},GetSrc:function(){return new D2L.Util.DelayedReturn(this.m_src)},GetWidth:function(){return this.m_size},GetHeight:function(){return this.m_size}});
D2L.Control.UserProfileBadge=D2L.Control.extend({Construct:function(userProfileBadgeInfo){arguments.callee.$.Construct.call(this);this.m_cacheBuster="";this.m_isDisplayed=true;this.m_orgId=0;this.m_size=100;this.m_userId=0;this.m_contextUserId=0;this.m_userProfileBadgeInfo=null;if(userProfileBadgeInfo!==undefined)this.m_userProfileBadgeInfo=userProfileBadgeInfo},BuildDom:function(){if(this.IsRendered())return;arguments.callee.$.BuildDom.call(this);this.SetDomNode(this.CreateElement("img"));var profilebadgeImage=
this.m_userProfileBadgeInfo.GetProfileBadgeImage();var delayedSrc=profilebadgeImage.GetSrc();var domNode=this.GetDomNode();var me=this;delayedSrc.Register(function(src){domNode.src=src;domNode.style.width=profilebadgeImage.GetWidth()+"px";domNode.style.height=profilebadgeImage.GetHeight()+"px"});this.m_userProfileBadgeInfo.GetProfileBadgeAlternativeText().AssignText(this.GetDomNode(),"alt")},IntegrateControlMin:function(deserializer){arguments.callee.$.IntegrateControlMin.call(this,deserializer);
this.m_isDisplayed=this.GetDomNode().style.display!="none";this.m_orgId=deserializer.GetMember();this.m_userId=deserializer.GetMember();this.m_size=deserializer.GetMember();this.m_cacheBuster=deserializer.GetMember();this.m_contextUserId=deserializer.GetMember()},IsDisplayed:function(){return this.m_isDisplayed},SetFile:function(json){var fileInfo=D2L.Serialization.JsonDeserializer.Deserialize(json,D2L.Files.FileInfo);this.GetDomNode().src="/d2l/common/viewprofileimage.d2l?"+"oi="+this.m_orgId+"&ui="+
this.m_userId+"&s="+this.m_size+"&lm="+fileInfo.GetLastModified()+"&v="+this.m_cacheBuster+"&cui="+this.m_contextUserId},SetIsDisplayed:function(isDisplayed){if(this.IsRendered())this.GetDomNode().style.display=isDisplayed?"inline":"none";this.m_isDisplayed=isDisplayed},SetProfileImage:function(profileImage){if(profileImage!==null)this.GetDomNode().src=D2L.Control.Thumbnail.GetViewThumbUrl(profileImage,this.m_size);else{var me=this;var img=new D2L.Images.ImageTerm("Framework.UserProfileBadge.actProfile"+
this.m_size);img.GetSrc().Register(function(src){me.GetDomNode().src=src})}}});
D2L.Control.UserProfileBadgeInfo=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_profileBadgeImage=null;this.m_profileBadgeAlternativeText=null},Deserialize:function(deserializer){this.m_profileBadgeImage=deserializer.GetObject("ProfileBadgeImage");this.m_profileBadgeAlternativeText=deserializer.GetObject("ProfileBadgeAlternativeText")},GetProfileBadgeImage:function(){return this.m_profileBadgeImage},GetProfileBadgeAlternativeText:function(){return this.m_profileBadgeAlternativeText}});
if(window["D2L"]!==undefined&&D2L.LP.Web.Packaging!==undefined)D2L.LP.Web.Packaging.Register("D2L.LP.Web.Controls.UserProfile.default");